export const ROUTES = {
  home: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  authCallback: "/auth/callback",
  jobs: "/jobs",
  jobDetail: (id: string) => `/jobs/${id}`,
  salary: "/salary",
  blog: "/blog",
  community: "/community",
  employer: "/employer",
  employerVerify: "/employer/verify",
  companyProfile: (slug: string) => `/companies/${slug}`,
  talent: "/talent",
  talentVerify: "/talent/verify",
  talentProfile: (slug: string) => `/talent/${slug}`,
  saved: "/saved",
  alerts: "/alerts",
  notifications: "/notifications",
  applicationDetail: (id: string) => `/applications/${id}`,
  applicationMessages: (id: string) => `/applications/${id}/messages`,
  applicationInterview: (id: string) => `/applications/${id}/interview`,
  settings: "/settings",
  employerDashboard: "/employer-dashboard",
  talentSearch: "/employer-dashboard/talent",
  team: "/employer-dashboard/team",
  interviewSchedule: "/employer-dashboard/interviews",
  teamInvite: (token: string) => `/team/invitations/${token}`,
  profile: "/profile",
  postJob: "/post-job",
  postJobSuccess: "/post-job/success",
  admin: "/admin",
} as const;
