export const ROUTES = {
  home: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  authCallback: "/auth/callback",
  jobs: "/jobs",
  jobDetail: (id: string) => `/jobs/${id}`,
  salary: "/salary",
  blog: "/blog",
  community: "/community",
  employer: "/employer",
  talent: "/talent",
  saved: "/saved",
  alerts: "/alerts",
  settings: "/settings",
  employerDashboard: "/employer-dashboard",
  profile: "/profile",
  postJob: "/post-job",
  postJobSuccess: "/post-job/success",
  admin: "/admin",
} as const;
